import { Users, Star, Phone, Mail, MapPin, Award, Heart, Globe } from "lucide-react";
import Image from "next/image";

const stats = [
  { value: "50,000+", label: "Happy Travelers" },
  { value: "100+",    label: "Destinations" },
  { value: "15+",     label: "Years Experience" },
  { value: "25+",     label: "Awards Won" },
];

const values = [
  {
    icon: <Heart className="w-5 h-5 text-[#B91C1C]" />,
    title: "Crafted with Care",
    description:
      "Every itinerary is hand-built by our travel experts — not generated by an algorithm. Your trip deserves that personal touch.",
  },
  {
    icon: <Globe className="w-5 h-5 text-[#2563EB]" />,
    title: "Local Knowledge",
    description:
      "We partner with local guides who know every hidden alley, off-menu dish, and secret viewpoint worth finding.",
  },
  {
    icon: <Award className="w-5 h-5 text-[#D97706]" />,
    title: "Trusted for 15 Years",
    description:
      "Over 50,000 travellers have placed their trust in us. That reputation is something we take seriously every single day.",
  },
  {
    icon: <Users className="w-5 h-5 text-[#059669]" />,
    title: "24 / 7 Support",
    description:
      "Whether it's 2 AM in Hanoi or noon in Ahmedabad, our team is reachable. Travel confidently knowing backup is a call away.",
  },
];

const offices = [
  {
    flag: "🇮🇳",
    country: "India — Headquarters",
    name: "Book Itinerary Tours & Travel",
    address: "SCF-37, Sector 11D, Haryana – 121006",
    note: null,
  },
  {
    flag: "🇦🇪",
    country: "Dubai, UAE",
    name: "Dubai Office",
    address: "Shop #03, AL Souq Al Kabeer, Meena Bazar, Burdubai, Dubai",
    note: "PO Box: 87867",
  },
  {
    flag: "🇸🇬",
    country: "Singapore",
    name: "Singapore Office",
    address: "291, Seragoon Road #01-01, Seragoon Building, Singapore 218107",
    note: "Near Sitara Restaurant",
  },
  {
    flag: "🇭🇰",
    country: "Hong Kong",
    name: "Hong Kong Office",
    address: "Cheung Lee Commercial Building, 25 Kimberley Road, Tsim Sha Tsui",
    note: "Licence No: 350318",
  },
];

const About = () => {
  return (
    <div className="min-h-screen bg-white text-[#111827]">

      {/* ── Hero ────────────────────────────────────────────────────────── */}
      <section className="relative pt-[68px] overflow-hidden">
        {/* Full-bleed image */}
        <div className="relative h-[480px] sm:h-[540px]">
          <Image
            src="https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1920&q=80"
            alt="Travel"
            fill
            className="object-cover"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/30 to-black/60" />

          <div className="absolute inset-0 flex items-end">
            <div className="max-w-[1200px] mx-auto w-full px-6 lg:px-8 pb-14">
              <p className="text-[12px] font-bold text-[#F59E0B] uppercase tracking-[0.2em] mb-3">
                Our Story
              </p>
              <h1 className="text-[2.6rem] sm:text-[3.4rem] font-extrabold text-white leading-tight max-w-2xl">
                Turning Destinations<br />
                into Memories
              </h1>
            </div>
          </div>
        </div>
      </section>

      {/* ── Stats bar ───────────────────────────────────────────────────── */}
      <section className="border-b border-[#F3F4F6]">
        <div className="max-w-[1200px] mx-auto px-6 lg:px-8">
          <div className="grid grid-cols-2 sm:grid-cols-4 divide-x divide-[#F3F4F6]">
            {stats.map((s) => (
              <div key={s.label} className="py-10 px-6 text-center">
                <p className="text-[2rem] sm:text-[2.4rem] font-extrabold text-[#111827] leading-none">
                  {s.value}
                </p>
                <p className="text-[13px] text-[#6B7280] font-medium mt-1.5">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Who we are ──────────────────────────────────────────────────── */}
      <section className="py-24 bg-white">
        <div className="max-w-[1200px] mx-auto px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">

            {/* Image */}
            <div className="relative">
              <div className="rounded-[20px] overflow-hidden shadow-[0_20px_60px_rgba(0,0,0,0.10)]">
                <Image
                  src="/bg-image/image.png"
                  alt="Our team"
                  width={580}
                  height={480}
                  className="w-full h-[420px] object-cover"
                />
              </div>
              {/* Floating badge */}
              <div className="absolute -bottom-5 -right-4 bg-white rounded-[16px] shadow-[0_8px_32px_rgba(0,0,0,0.12)] border border-[#F3F4F6] px-5 py-4 flex items-center gap-3">
                <div className="text-3xl">🏆</div>
                <div>
                  <p className="text-[13px] font-extrabold text-[#111827]">Industry Leader</p>
                  <p className="text-[12px] text-[#6B7280]">25+ Awards &amp; Recognition</p>
                </div>
              </div>
            </div>

            {/* Text */}
            <div>
              <p className="text-[11px] font-extrabold text-[#F59E0B] uppercase tracking-[0.2em] mb-3">
                Who We Are
              </p>
              <h2 className="text-[2rem] sm:text-[2.4rem] font-extrabold text-[#111827] leading-tight mb-5">
                More than a travel agency —<br />
                <span className="text-[#2563EB]">a journey partner</span>
              </h2>
              <div className="w-10 h-[3px] bg-[#F59E0B] rounded-full mb-7" />

              <div className="space-y-5 text-[15px] text-[#374151] leading-relaxed">
                <p>
                  Founded in <strong>2008</strong>, Book Itinerary began as a small passion project to make
                  extraordinary travel accessible to everyone in India. Today we're one of the country's
                  most trusted names in curated travel.
                </p>
                <p>
                  We believe travel is more than ticking off landmarks. It's about <strong>connecting
                  with cultures</strong>, slowing down in the right places, and coming home changed.
                </p>
                <p>
                  Every package we offer is personally verified by our team — so what you see is
                  exactly what you get.
                </p>
              </div>

              <div className="flex flex-wrap gap-3 mt-8">
                <div className="flex items-center gap-2 bg-[#FFFBEB] border border-[#FDE68A] rounded-full px-4 py-2">
                  <Star className="h-3.5 w-3.5 fill-[#F59E0B] text-[#F59E0B]" />
                  <span className="text-[13px] font-semibold text-[#92400E]">4.9 / 5 Rating</span>
                </div>
                <div className="flex items-center gap-2 bg-[#EFF6FF] border border-[#DBEAFE] rounded-full px-4 py-2">
                  <Users className="h-3.5 w-3.5 text-[#2563EB]" />
                  <span className="text-[13px] font-semibold text-[#1D4ED8]">50,000+ Travelers</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Values ──────────────────────────────────────────────────────── */}
      <section className="py-24 bg-[#F8FAFC]">
        <div className="max-w-[1200px] mx-auto px-6 lg:px-8">

          <div className="text-center mb-14">
            <p className="text-[11px] font-extrabold text-[#F59E0B] uppercase tracking-[0.2em] mb-3">
              Why Choose Us
            </p>
            <h2 className="text-[2rem] sm:text-[2.4rem] font-extrabold text-[#111827] leading-tight">
              What sets us apart
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {values.map((v, i) => (
              <div
                key={i}
                className="bg-white rounded-[18px] border border-[#E5E7EB] p-7 hover:shadow-[0_12px_40px_rgba(0,0,0,0.07)] hover:-translate-y-1 transition-all duration-200"
              >
                <div className="w-10 h-10 rounded-[10px] bg-[#F8FAFC] border border-[#E5E7EB] flex items-center justify-center mb-5">
                  {v.icon}
                </div>
                <h3 className="text-[15px] font-bold text-[#111827] mb-2">{v.title}</h3>
                <p className="text-[13px] text-[#6B7280] leading-relaxed">{v.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Contact ─────────────────────────────────────────────────────── */}
      <section className="py-24 bg-white">
        <div className="max-w-[1200px] mx-auto px-6 lg:px-8">

          <div className="text-center mb-14">
            <p className="text-[11px] font-extrabold text-[#F59E0B] uppercase tracking-[0.2em] mb-3">
              Get In Touch
            </p>
            <h2 className="text-[2rem] sm:text-[2.4rem] font-extrabold text-[#111827] leading-tight">
              We'd love to hear from you
            </h2>
          </div>

          {/* Contact links */}
          <div className="flex flex-col sm:flex-row justify-center gap-4 mb-16">
            <a
              href="tel:+919315666960"
              className="flex items-center gap-4 bg-[#F8FAFC] border border-[#E5E7EB] rounded-[14px] px-6 py-4 hover:border-[#2563EB] hover:bg-[#EFF6FF] transition-all duration-200 group"
            >
              <div className="w-10 h-10 rounded-full bg-[#FFFBEB] border border-[#FDE68A] flex items-center justify-center shrink-0">
                <Phone className="h-4 w-4 text-[#D97706]" />
              </div>
              <div>
                <p className="text-[11px] text-[#9CA3AF] font-semibold uppercase tracking-wider mb-0.5">Call Us</p>
                <p className="text-[15px] font-bold text-[#111827] group-hover:text-[#2563EB] transition-colors">
                  +91 93156 66960
                </p>
              </div>
            </a>
            <a
              href="mailto:info@bookitinerary.com"
              className="flex items-center gap-4 bg-[#F8FAFC] border border-[#E5E7EB] rounded-[14px] px-6 py-4 hover:border-[#2563EB] hover:bg-[#EFF6FF] transition-all duration-200 group"
            >
              <div className="w-10 h-10 rounded-full bg-[#EFF6FF] border border-[#DBEAFE] flex items-center justify-center shrink-0">
                <Mail className="h-4 w-4 text-[#2563EB]" />
              </div>
              <div>
                <p className="text-[11px] text-[#9CA3AF] font-semibold uppercase tracking-wider mb-0.5">Email Us</p>
                <p className="text-[15px] font-bold text-[#111827] group-hover:text-[#2563EB] transition-colors">
                  info@bookitinerary.com
                </p>
              </div>
            </a>
          </div>

          {/* Offices */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {offices.map(({ flag, country, name, address, note }) => (
              <div
                key={country}
                className="bg-[#F8FAFC] border border-[#E5E7EB] rounded-[18px] p-6 hover:shadow-[0_8px_32px_rgba(0,0,0,0.07)] hover:-translate-y-0.5 transition-all duration-200"
              >
                <span className="text-[28px] block mb-4">{flag}</span>
                <p className="text-[10px] font-extrabold text-[#2563EB] uppercase tracking-widest mb-1">
                  {country}
                </p>
                <p className="text-[14px] font-bold text-[#111827] mb-2 leading-snug">{name}</p>
                <div className="flex items-start gap-1.5 text-[12px] text-[#6B7280] leading-relaxed">
                  <MapPin className="w-3.5 h-3.5 text-[#9CA3AF] shrink-0 mt-0.5" />
                  <span>{address}</span>
                </div>
                {note && (
                  <span className="inline-block mt-3 text-[11px] font-semibold text-[#D97706] bg-[#FFFBEB] border border-[#FDE68A] rounded-full px-3 py-1">
                    {note}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Bottom CTA ──────────────────────────────────────────────────── */}
      <section className="py-20 bg-[#111827]">
        <div className="max-w-[700px] mx-auto px-6 text-center">
          <p className="text-[11px] font-extrabold text-[#F59E0B] uppercase tracking-[0.2em] mb-4">
            Ready to travel?
          </p>
          <h2 className="text-[2rem] sm:text-[2.6rem] font-extrabold text-white leading-tight mb-6">
            Your next adventure<br />is one click away.
          </h2>
          <p className="text-[#9CA3AF] text-[15px] mb-8 leading-relaxed">
            Browse our handpicked packages or talk to one of our travel experts to plan something truly personal.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a
              href="/packages"
              className="inline-flex items-center justify-center gap-2 bg-[#F59E0B] hover:bg-[#D97706] text-white font-bold px-8 py-3.5 rounded-[12px] text-[14px] transition-all duration-200 hover:shadow-lg"
            >
              Browse Packages
            </a>
            <a
              href="/contact"
              className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/15 text-white font-semibold px-8 py-3.5 rounded-[12px] text-[14px] border border-white/20 transition-all duration-200"
            >
              Talk to an Expert
            </a>
          </div>
        </div>
      </section>

    </div>
  );
};

export default About;
